
export const GOOGLE_USER_LOGIN = 'GOOGLE_USER_LOGIN';
export const GOOGLE_USER_LOGIN_SUCCESS = 'GOOGLE_USER_LOGIN_SUCCESS';
export const GOOGLE_USER_LOGIN_FAILURE = 'GOOGLE_USER_LOGIN_FAILURE';

export const APPLE_USER_LOGIN = 'APPLE_USER_LOGIN';
export const APPLE_USER_LOGIN_SUCCESS = 'APPLE_USER_LOGIN_SUCCESS';
export const APPLE_USER_LOGIN_FAILURE = 'APPLE_USER_LOGIN_FAILURE';



export const USER_EMAIL_LOGIN = 'USER_EMAIL_LOGIN';
export const USER_EMAIL_LOGIN_SUCCESS = 'USER_EMAIL_LOGIN_SUCCESS';
export const USER_EMAIL_LOGIN_FAILURE = 'USER_EMAIL_LOGIN_FAILURE';

export const TFA_STARTED = 'TFA_STARTED';
export const VERIFY_OTP = 'VERIFY_OTP';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAILURE = 'VERIFY_OTP_FAILURE';
export const CLEAR_OTP_ERROR = 'CLEAR_OTP_ERROR';

