
export const GOOGLE_USER_LOGIN = 'GOOGLE_USER_LOGIN';
export const GOOGLE_USER_LOGIN_SUCCESS = 'GOOGLE_USER_LOGIN_SUCCESS';
export const GOOGLE_USER_LOGIN_FAILURE = 'GOOGLE_USER_LOGIN_FAILURE';

export const APPLE_USER_LOGIN = 'APPLE_USER_LOGIN';
export const APPLE_USER_LOGIN_SUCCESS = 'APPLE_USER_LOGIN_SUCCESS';
export const APPLE_USER_LOGIN_FAILURE = 'APPLE_USER_LOGIN_FAILURE';

export const USER_EMAIL_LOGIN = 'USER_EMAIL_LOGIN';
export const USER_EMAIL_SIGNUP = 'USER_EMAIL_SIGNUP';
export const USER_EMAIL_SIGNUP_VERIFY_OTP = 'USER_EMAIL_SIGNUP_VERIFY_OTP';
export const USER_EMAIL_LOGIN_SUCCESS = 'USER_EMAIL_LOGIN_SUCCESS';
export const USER_EMAIL_SIGN_UP_OTP_SUCCESS = 'USER_EMAIL_SIGN_UP_OTP_SUCCESS';
export const USER_EMAIL_SIGN_UP_OTP_FAILURE = 'USER_EMAIL_SIGN_UP_OTP_FAILURE';
export const USER_EMAIL_LOGIN_FAILURE = 'USER_EMAIL_LOGIN_FAILURE';

export const TFA_STARTED = 'TFA_STARTED';
export const VERIFY_OTP = 'VERIFY_OTP';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAILURE = 'VERIFY_OTP_FAILURE';
export const CLEAR_OTP_ERROR = 'CLEAR_OTP_ERROR';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const VALIDATE_RESET_PASSWORD_OTP = 'VALIDATE_RESET_PASSWORD_OTP';
export const VALIDATE_RESET_PASSWORD_OTP_SUCCESS = 'VALIDATE_RESET_PASSWORD_OTP_SUCCESS';
export const VALIDATE_RESET_PASSWORD_OTP_FAILURE = 'VALIDATE_RESET_PASSWORD_OTP_FAILURE';

export const OTP_SCREEN_UNMOUNTING = 'OTP_SCREEN_UNMOUNTING';

export const SET_LOGOUT_TIMER = 'SET_LOGOUT_TIMER';
export const CLEAR_LOGOUT_TIMER = 'CLEAR_LOGOUT_TIMER';