
export const GET_COMPANY_BRANCH_LIST = 'GET_COMPANY_BRANCH_LIST';
export const GET_COMPANY_BRANCH_LIST_SUCCESS = 'GET_COMPANY_BRANCH_LIST_SUCCESS';
export const GET_COMPANY_BRANCH_LIST_FAILURE = 'GET_COMPANY_BRANCH_LIST_FAILURE';


