export const GET_COMPANY_BRANCH_LIST = 'GET_COMPANY_BRANCH_LIST';
export const GET_COMPANY_BRANCH_LIST_SUCCESS = 'GET_COMPANY_BRANCH_LIST_SUCCESS';
export const GET_COMPANY_BRANCH_LIST_FAILURE = 'GET_COMPANY_BRANCH_LIST_FAILURE';
export const GET_COMPANY_DETAILS = 'GET_COMPANY_DETAILS';
export const SET_COMPANY_DETAILS = 'SET_COMPANY_DETAILS';
export const SET_COMPANY_VOUCHER_VERSION = 'SET_COMPANY_VOUCHER_VERSION';

export const RENEW_ACCESS_TOKEN = 'RENEW_ACCESS_TOKEN';
export const LOGOUT = 'LOGOUT';
export const RESET = 'RESET';
export const SHOW_ADD_BUTTON_SHEET = 'RESET';
export const IS_UNAUTHORSIED = 'IS_UNAUTHORISED';
export const IS_AUTHORSIED = 'IS_AUTHORISED';
export const SET_VOUCHER_FOR_BOTTOM_TABS = 'IS_AUTHORSIED';
export const GET_STATE_DETAILS = 'GET_STATE_DETAILS';
export const UPDATE_STATE_DETAILS = 'UPDATE_STATE_DETAILS';
export const UPDATE_BRANCH_STATE_DETAILS = 'UPDATE_BRANCH_STATE_DETAILS';
