export const GET_COMPANY_BRANCH_LIST = 'GET_COMPANY_BRANCH_LIST';
export const GET_COMPANY_BRANCH_LIST_SUCCESS = 'GET_COMPANY_BRANCH_LIST_SUCCESS';
export const GET_COMPANY_BRANCH_LIST_FAILURE = 'GET_COMPANY_BRANCH_LIST_FAILURE';
export const GET_COMPANY_DETAILS = 'GET_COMPANY_DETAILS';
export const SET_COMPANY_DETAILS = 'SET_COMPANY_DETAILS';
export const SET_COMPANY_VOUCHER_VERSION = 'SET_COMPANY_VOUCHER_VERSION';

export const RENEW_ACCESS_TOKEN = 'RENEW_ACCESS_TOKEN';
export const LOGOUT = 'LOGOUT';
export const RESET = 'RESET';
export const SHOW_ADD_BUTTON_SHEET = 'RESET';
export const IS_UNAUTHORSIED = 'IS_UNAUTHORISED';
export const IS_AUTHORSIED = 'IS_AUTHORISED';
export const SET_VOUCHER_FOR_BOTTOM_TABS = 'IS_AUTHORSIED';
export const GET_STATE_DETAILS = 'GET_STATE_DETAILS';
export const UPDATE_STATE_DETAILS = 'UPDATE_STATE_DETAILS';
export const UPDATE_BRANCH_STATE_DETAILS = 'UPDATE_BRANCH_STATE_DETAILS';
export const RESET_ACCOUNT_SEARCH = 'RESET_ACCOUNT_SEARCH';
export const UPDATE_ACCOUNT_SEARCH = 'UPDATE_ACCOUNT_SEARCH';
export const SET_BIOMETRIC_TOUR_ENABLED = 'SET_BIOMETRIC_TOUR_ENABLED';

// Subscription Constants

export const GET_SUBSCRIPTION_PLANS = 'GET_SUBSCRIPTION_PLANS';
export const SET_SUBSCRIPTION_PLANS = 'SET_SUBSCRIPTION_PLANS';
export const GET_COUNTRY_LIST = 'GET_COUNTRY_LIST';
export const SET_COUNTRY_LIST = 'SET_COUNTRY_LIST';
export const SET_SELECTED_COUNTRY = 'SET_SELECTED_COUNTRY';
export const SET_SELECTED_PLAN = 'SET_SELECTED_PLAN';
export const SET_PROMO_CODE = 'SET_PROMO_CODE';
export const APPLY_PROMO_CODE = 'APPLY_PROMO_CODE';
export const SET_APPLIED_PROMO_CODE = 'SET_APPLIED_PROMO_CODE';
export const SET_IS_MONTHLY_PLAN = 'SET_IS_MONTHLY_PLAN';
export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES';
export const SET_ALL_COUNTRIES = 'SET_ALL_COUNTRIES';
export const GET_COUNTRY_STATES = 'GET_COUNTRY_STATES';
export const SET_COUNTRY_STATES = 'SET_COUNTRY_STATES';
export const SET_FORM_DATA = 'SET_FORM_DATA';
export const GET_PLAN_SUMMARY_AMOUNT = 'GET_PLAN_SUMMARY_AMOUNT';
export const SET_PLAN_SUMMARY_AMOUNT = 'SET_PLAN_SUMMARY_AMOUNT';
export const START_TRIAL = 'START_TRIAL';
export const SET_SUBSCRIPTION_DATA = 'SET_SUBSCRIPTION_DATA';
export const SET_IS_LOADING = 'SET_IS_LOADING';
