export default {
  Home: 'home',
  Login: 'login',
  Password: 'Password',
  ResetPassword: 'ResetPassword',
  Otp: 'Otp',
  Signup: 'Signup',
  createCompany:'createCompany',
  createCompanyDetails:'createCompanyDetails',
  Dashboard: 'dashboard',
  Inventory: 'inventory',
  Accounts: 'accounts',
  Add: 'add',
  Parties: 'parties',
  More: 'more',
  Transaction: 'transaction',
  BigButton: 'bigButton',
  Welcome: 'Welcome',
  CompanyInfoOne: 'CompanyInfoOne',
  CompanyInfoTwo: 'CompanyInfoTwo'
};
