export default {
  Home: 'home',
  Login: 'login',
  Password: 'Password',
  Otp: 'Otp',
  Dashboard: 'dashboard',
  Inventory: 'inventory',
  Add: 'add',
  Parties: 'parties',
  More: 'more',
  Transaction: 'transaction',
  BigButton: 'bigButton',
  Welcome: 'Welcome',
  CompanyInfoOne: 'CompanyInfoOne',
  CompanyInfoTwo: 'CompanyInfoTwo',
};
